### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by rybakit** [php-decimal/ext-decimal#43]
I get these errors when trying to build this extension with PHP 8.0.0-dev: https://travis-ci.org/github/tarantool-php/client/jobs/691042435#L661

**Comment by andypost** [comment]
Trying to build with PHP 8.0 fails the same way
````
/tmp/pear/temp/decimal/php_decimal.h:191:60: error: initializer element is not constant
         {(const char*)(zend_uintptr_t)(required_num_args), ZEND_TYPE_ENCODE_CLASS_CONST(PHP_DECIMAL_FQCN, 0), 0, 0},
                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by zlodes** [comment]
@andypost You must change it with `ZEND_TYPE_INIT_CLASS_CONST`. 

And... I am working on PHP8 Support for decimal 1.x. I think I will have completed at next weekend.

**Comment by andypost** [comment]
@zlodes thanks for idea, I'm digging a state of extensions and gonna help as I can. Is there any WIP repo?

**Comment by zlodes** [comment]
@andypost created draft PR: https://github.com/php-decimal/ext-decimal/pull/53

**Comment by ICJR** [comment]
@rtheunissen will you be merging @zlodes PR to support 1.x and/or 2.x on PHP8 soon?

**Comment by zlodes** [comment]
@ICJR This PR has trouble with reflection test. It prints that null is allowed for some methods. 

I don't know how to fix it...

**Comment by rtheunissen** [comment]
1.x now has support, but I will leave this open until 2.x is also done.

**Comment by rtheunissen** [comment]
PHP 8.0+ supported since v1.4.0. PHP 8.2, 8.3, and 8.4 supported in v2.0.0.
